steps:
  - name: node:16.20.0
    entrypoint: npm
    args: ["install"]
  - name: node:16.20.0
    entrypoint: npm
    args: ["run", "build"]
  - name: node:16.20.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "PG_HOST=${_PG_HOST}"
      - "PG_PORT=${_PG_PORT}"
      - "PG_DATABASE=${_PG_DATABASE}"
      - "PG_USER=${_PG_USER}"
    secretEnv: ["PG_PASSWORD", "GOOGLE_APPLICATION_CREDENTIALS"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "./staging.yaml"]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/WAVLAKE_ALPHA_FIREBASE_ADMIN_CONFIG/versions/latest
      env: "GOOGLE_APPLICATION_CREDENTIALS"
    - versionName: projects/$PROJECT_ID/secrets/WAVLAKE_PROD_PG_CATALOG_PASSWORD/versions/latest
      env: "PG_PASSWORD"
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
